### ISSUE TITLE
Secondary objectives fail to notify properly when there is only one major city left to liberate

### ISSUE THREAD

**Issue by mwpowellhtx** [KillahPotatoes/KP-Liberation#399]
Subject says it all. Don't know which version(s) specifically we're talking about. Maybe this has since been fixed. I've also heard reports from some of the guys I engage alongside that a "FOB", for instance, may well be there, somewhere, stacking up, per se, but the circle does not get reported, or the question mark, or a message to those that have joined the fray. It's a simple enough mod for the "unwashed", so to speak; but also so much depth and replay value. Thanks!

**Comment by mwpowellhtx** [comment]
I figure as much; there is not enough of the game mode left to justify a secondary objective. Perhaps the options should just be removed and/or disabled when that's the case, if possible.

**Comment by Wyqer** [comment]
Yeah, I've already thought about a "remove it when not possible". But I guess then the reports of "can't start secondary objectives, this has to be a bug" will increase enormously.
So a quick "You've advanced too far in the current campaign, no secondary missions possible" or similar and return the spent intel points (even if they're useless from that point). Maybe the whole secondary mission behaviour etc. will change due to the refactoring.
We'll see how it'll be at 0.97.

**Comment by mwpowellhtx** [comment]
@Wyqer IDK, to me it's more troubling that intel vanishes and finding no secondary come up.

**Comment by Wyqer** [comment]
>So a quick "You've advanced too far in the current campaign, no secondary missions possible" or similar and return the spent intel points (even if they're useless from that point).

And with a hint like mentioned before you know why.
