### ISSUE TITLE
devkit attributes

### ISSUE THREAD

**Issue by gelir95** [KillahPotatoes/KP-Liberation#401]
The devkit is missing General... (Titel, Author) and Multiplayer... (Game Type, Players, Summary, Respawn)   Attributes. This could lead to confusion. Furthermore this should be included into the wiki.
I attached a "fixed version"
[kp_liberation_devkit.VR.zip](https://github.com/KillahPotatoes/KP-Liberation/files/1976587/kp_liberation_devkit.VR.zip)

**Comment by Wyqer** [comment]
The devkit was meant to just provide the eden stuff you need to place down in your mission, nothing more basically.
The description.ext comes with the framework itself, which contains mission name stuff etc.

Haven't looked in the provided zip, but as it's here, maybe some people benefit from it.

With 0.97 the wiki and the mission itself will be different, therefore there will be a new devkit.
Due to this, there won't be any update on the current framework files anymore.

But many thanks to provide this to the playerbase. 👍
