### ISSUE TITLE
Marker of Informer too close to position of informant

### ISSUE THREAD

**Issue by madpat3** [KillahPotatoes/KP-Liberation#461]
## Suggestion/Feature request
the "question mark-marker" when an "informant-sidemission" is activated, is always right on spot, where the informant is located. 

### Describe the solution you'd like:
place the question mark right in the middle of the sector, where the informant is to find.

**Comment by alexbobp** [comment]
Is it possible to call this back into question?  Or at least to ask for someone to give the rationale for this change?

Why would a civilian informant *not* tell you their address, and make you search?
Why would anyone find searching door to door in an un-occupied town to be good gameplay?

If it's possible, I'd like to re-open the conversation about this rather than just treat it as an automatically good feature, so that players can know why they are spending so much time searching door to door for someone who was supposed to be offering up information voluntarily.

**Comment by Wyqer** [comment]
That was requested over one year ago and implemented about a half year ago.
Won't be opened anymore.
If you want to change it in your missionfile, have a look at the commit which changed the behavior:
https://github.com/KillahPotatoes/KP-Liberation/pull/598/commits/7d4271cb0e3a7097a56b3114b71d848aa80ecac9

**Comment by alexbobp** [comment]
Ok.  But I can't ask for a quick one-sentence answer on why this feature makes any sense, either gameplay wise or thematically?

**Comment by Wyqer** [comment]
>  But I can't ask for a quick one-sentence answer

You did, so you obviously can.

As said it was requested and we decided to implement it. If you want some „in game reasoning“, think about the informant couldn’t tell you via comms where he exactly hides or whatever. Beside of that, it’s an easy revert, as linked. Don’t see any issue.

**Comment by alexbobp** [comment]
Well the issue is providing the vast majority of players with a terrible game experience.  Yes, I can and did customize it on my server, but defaults matter.

If the excuse is that there is a risk of opfor showing up to search for the informant, then that should actually *happen,* and the search for the informant wouldn't be so incredibly boring if you also had to ward off a patrol.

**Comment by veteran29** [comment]
>Well the issue is providing the vast majority of players with a terrible game experience

Well, you're the first one saying/having an issue with that, actually the author of this issue had opposite toughs. We do not intend to change that as current legacy code base is not that actively developed anymore and we do not see it as a big issue.

I would not be against making changes to that particular side mission but I won't spend any of my own time on it right now.

**Comment by alexbobp** [comment]
No, I'm the first one to bother to leave feedback.  I know from numerous Liberation servers I play on that many other server admins have reverted the same change.  But I'll stand down and see if anyone else has input.
