### ISSUE TITLE
Add resources system to virtuell arsenal

### ISSUE THREAD

**Issue by madpat3** [KillahPotatoes/KP-Liberation#501]
### Is your feature request related to a problem? Please describe:
No

### Describe the solution you'd like:
I just found a script, which adds a "money system" to the virtuell arsenal. So you need money for the gear you get from the arsenal. Why not modify it and integrate it into the mission, so you need certain resources like supply and ammunition, to get the gear you want? Just like as if you buy certain vehicles and other stuff.

### Additional context:
Link to the script: [http://www.armaholic.com/page.php?id=34506](url)

**Comment by Wyqer** [comment]
Beside that we won't implement 3rd party scripts (dependency concerning updates, license stuff, mostly don't suit our needs for 100%, etc.) I personally dislike the gameplay mechanic of "buy your gear with cash". It's just an immersion thing, but it's a subjective thing, of course.
We've already thought about a "no arsenal" option where you build crates with equipment for resources. These crates has to be transported to the troops to resupply or have to take their gear from the crates you've stored in your FOB.

The script itself looks very easy to implement for anyone who is interested, so it's no big deal to implement it in an own edited version.
This is the repository by the way: https://github.com/7erra/Arsenal-Shop

So this will be stated as "denied" due to the fact of a third party script, but the idea itself is already something we've on our mind.

**Comment by madpat3** [comment]
i'm fine with the crates solution.
