### ISSUE TITLE
Suggestion / Feature request: Variable Armory / Arsenal

### ISSUE THREAD

**Issue by Nopus64** [KillahPotatoes/KP-Liberation#592]
### Is your feature request related to a problem? Please describe:
No. Its a Idea i got from a other mission where i saw it.

### Describe the solution you'd like:
I am pretty sure, Wyqer also saw the mission "Antistasi". Were you play as a rebellion soldier and try to take over the City.
One of the nice Features i like in it is the Arsenal with unlockable new weapons and attachements (and others ...). I would had the idea of a "normal" army like we play in liberation but also to have the chance to get from side missions and others stuff. Some special equipment. (50. cal ...., maybe also vehicles ). I don t mind to go into Spec. Ops. stuff.

### Additional context:
This is just an idea may you can also extend that to other things.

### Where to finde the Arsenal Script ?
I try to find in the mission file from Antistasi because its not made from them. But need a bit Time for it.

**Comment by veteran29** [comment]
The arsenal used by Antistasi is named "[Jeroen Arsenal](https://github.com/Jeroen-Notenbomer/Limited-Arsenal)". 

As we're trying to keep our codebase clean we're not accepting external scripts for Liberation.

Personally I could see us implementing a way to add unlockables to arsenal that can be paid for with resources. For eg. pay X ammo to unlock certain weapon in arsenal.

But please don't expect that it will be added soon/0.97.0.

**Comment by Nopus64** [comment]
Its no the idea to copy past ist. I just like the idea behinde it. I know Antisasi is a not coded well.
May you can do something with the Idea maybe not.
I am happy how the project runs now and also how you guys look for the future. ;)

**Comment by tyl3r99** [comment]
i do also like the idea where you have to find  x amounts of a particular weapon/bring them back to base/load them into the arsenal or lets say FOB to unlock them.

brings a little of the resistance to liberation.

**Comment by Wyqer** [comment]
> brings a little of the resistance to liberation.

Which isn't the "aim" of Liberation, but from Antistasi.
Liberation should feel like playing as a Commander of regulars, not resistance.

**Comment by tyl3r99** [comment]
yeah i thought that as soon as i posted it..

**Comment by Daeburon** [comment]
perhaps instead then, there could be a means for Bluefor to help upgrade/unlock gear or skill upgrades for the resistance that helps the player if rep is high enough. 

this happens in real life when US/NATO is helping some 3rd world force. their "army" might still be using ancient M1 Garands or rusted out SKS's. we might give them more modern rifles, or force multipliers like NVGs or something. (then we hope the equipment doesnt fall into the wrong hands if things change!) if the country becomes stable enough, and maintains good diplomatic relations to stay on this path, they might one day even get hand-me-down F-16 jets or something.

so maybe when resistance rep is high enough, it unlocks some side missions: 

deliver X supply crates to this resistance camp. success will give the resistance squads better armor. 

deliver Y ammo crates to that camp, success adds men with AA/AT launchers to their squads.

deliver X/Y/Z supply/ammo/fuel crates, it upgrades their Technicals to Striders.

maybe have a mission that involves a joint Bluefor/resistance training operation, where joint task force works together to complete some objective. success means a skill upgrade for the resistance. 

something hilarious I realize about this, is that if the player does this, upgrades the resistance gear for them, then ends on their bad side again (kills too many civilians, etc) the resistance could become enemies once more. theyd use the gear you unlocked for them against you. so instead of them planting IEDs, its the APERS or SLAM mines you gave them. OOPS. 

maybe these could be general/vague upgrades for resistance, or maybe really specific stuff depending what makes more sense.

i think this kind of thing could be a good resource sink for players in the late game where they have so many factories that theyve reached a "post scarcity" resource economy.

**Comment by Wyqer** [comment]
It is planned for post 0.97.0 to extend the resistance aspects with more sidemission like "deliver weapons/assets" to increase their strength.

**Comment by Daeburon** [comment]
nice. i love it.

**Comment by Wyqer** [comment]
Always remember to check the created tasks/issues:
https://github.com/KillahPotatoes/KP-Liberation/issues/528

**Comment by syncy34** [comment]
Hey folks,

at first i'd like to say... i really love your mission and the way u are working on it.

Now i would like to add something to this suggestion.
Maybe it is better for regular forces to buy weapons instead of collecting it.

So maybe u could implement a limited arsenal (like Antistasi) with some fixed  stock items (defined by the mission maker) and give the commander or permitted players the option to order special weapons and ammunition from your factories.

The factory could use the produced resources to "craft" the weapons ore ammunition and after a given time a convoy starts to move to the nearest FOB (ore something like that). Then u must protect the convoy in order to get the weapons.

Maybe this could fit better for regular forces and brings in some new tactical components (and logistic works :D ).

At last... keep up the good work :D


ps: sorry for my english, i'm not a native speaker :)

**Comment by Nopus64** [comment]
haha Thanks for the big interest. But that was what i am aiming for. One Idea. For sure not the best and also not all hit the way how you Devs want to go with the Liberation. But i am pretty sure we can get a good concept out of it. How you want the mission looks like and how the players want to have it. ;)

As @Daeburon has written. There could be some possability to do more with the Ressources / Intel but i would do also some stuff like. A Resistance Leader where we can "talk" (getting a resuplly mission or so) or randomly unlock stuff. I also liked the idea of getting Vehicles from a City back to a FOB to unluck them. But as i had it some weeks ago. I tried to slign load a tank and an other time a plane. They dropped server times. No Fuel, and some sort of dmg they got too. And it wasn t possible to bring them back home. But i am pretty sure there is an other way to get them home too. ;)

**Comment by tyl3r99** [comment]
Anything's possible just whether the work it takes to do is deemed viable for them as it could take time.

But buying weaponry does sound cool.. Maybe weapons run out so we need to buy more shipments with supplies

Gun shipment - adds 10 of each gun in arsenal
Ammo shipment - adds so on

Equipment shipment - so on and on you get where I'm going?



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by Wyqer** [comment]
Now a duplicate to #594 and therefore closed.
