### ISSUE TITLE
Alternative to the virtual arsenal [discussion state]

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#594]
### Short Summary
As server admin I want to be able to select an alternative way to the virtual arsenal for my players to get their gear, so that we have some more realistic feeling about this in our group.

### Description
Currently we've the same mechanic like in the old framework and many other similar missions: the players get their equipment from the virtual arsenal or a very similar way.
We discussed internally about an alternative to this approach as an optional (default disabled) addition to the virtual arsenal. We would like to provide this additional mechanic, but think it won't be added in 0.97.0 but maybe in 0.97.1 or 0.98.0, depending on our mood and workload for other general mechanics.

In our discussions we've come to two possible ways to provide gear without the virtual arsenal (so there wouldn't be a virtual arsenal available, if the admin decides to use this alternative):
* **First Idea:** Players have to buy crates via the build menu with a specific content. The buildable crates would be defined in a kind of "crates preset", which holds information about crate type, the content of this particular crate and its price. So it would be possible to define amount X of crates for specific weapons, magazines, gear, uniforms, launchers, etc. This would be not that time consuming to adjust/create presets for personal liking. Crate for assault rifles, sniper rifles, spec ops crate with clothes and weapons, etc. would be possible with the preset file for the crates.
* **Second Idea:** Relying on the KP Cratefiller as logistic tool. So you would create (or buy) an empty crate type and fill it in the cratefiller for resources. This would mean there would be a list/preset for all available weapons/items/magazines/etc. with individual prices or kind of categories with category prices (LMG magazines, sniper rifle magazines, grenades, assault rifles, uniforms, helmets, etc.). You would fill your crate, get information about the whole costs for this "filling" and hit a fill/pay button. This would be more flexible in the game, but also more time consuming concerning creating own presets and filling crates during a running session, even if you would be able to save "crate inventory" inside the cratefiller and can prepare your "usual crates for the troops".

As we're not completely sure which would be the best way (especially concerning the amount of time a server admin would need to maintain it), we wanted to open this dev task already to collect opinions or maybe even more ideas than the two we've identified. So we're looking forward to your feedback.

Once we're close to implementing this feature we'll "close" the discussion and edit this issue to a full dev task with specific information about the way we've chosen to implement.

### Sub-Tasks
- [ ] Get Feedback/Ideas on this task

**Comment by tyl3r99** [comment]
I love this ^^^^

**Comment by Daeburon** [comment]
simple idea:

the game already charges like 30 supply for a basic rifleman AI, 50 for various specialists, etc. isnt equipping the player basically the same thing/the same abstract?

how about if you have to load crates with 100 supply points, and then if a player wants to access the arsenal from the crate, it just removes 25 points from the crate, (or however much). when all the points have been used, players cannot access arsenal from it until its refilled from nearby a fob supply depot. it could be easy to balance by just changing how much supply you can put in a crate and how much it costs to get an arsenal preset from it. 

note that if players want specific collections of gear to bring along as additional supplies for a mission, we could do that through the above system and making more arsenal presets with said gear in backpacks. so, for example, i could make an arsenal preset that just has a backpack with some AT missiles in it. i could make another with the sniper rifle, a scope, and some ammo for it in a backpack. yet another with mines and claymores in a backpack. then suppose we are getting ready for a mission and we expect heavy tanks...i might access the arsenal (and pay 25 supply or however much) to do so, buy the missile backpack, then carry it to the helicopter/truck and put the backpack in the vehicle inventory. then id go back to the arsenal box and buy my regular loadout. later, when we run into tanks, i have to return to the helicopter, remove the backpacks and get the missiles out.

i feel like players would adapt to this quickly. the moment you start charging for arsenal, the player will instinctively want to game the system by getting the most gear per arsenal use...so players will do things like buy a backpack full of 6.5mm ammo and 40mm grenades for the GL, because if they survive a mission, its cheaper to re-arm from that backpack several times than to pay full price just for a mags.

to me, this sounds very similar to your first idea, but using backpacks instead of crates...(and because backpacks is a vanilla feature, probably requires a lot less coding!). backpacks might be better too, because players can already carry them, making it a little easier to handle/transport around the fob.

**Comment by HeliceWolf** [comment]
I like the idea of buy the personal gear and pay for better weapons/Equipment. In fact i am working in a fusion of KPliberation with the HG Simple shop. (wich i think is is going to be paused after see your ideas).

I don't like the idea of more work for the admin server. Also it is true using virtual arsenal is time consuming for the player, but you know, my friends love waste time in the "fashion Arma" and prepare a set for medic, another set for antitank, another as grenadier etc etc. Thats the reason we always use RHS version and TRYKs multiplay uniforms.

I really don't want to disable the option they prepare their own sets. Obiously this will be different in other communities where exist a uniform politics. We are more like mercenary or operators and we enjoy it.

So, i like the idea of personal crates (defined by the players) where people can save theyr own presets. (and if someone dies they just can buy it again very fast. Paying the price off course).

///////////////////////
Details:

I would like still use the ace virtual arsenal UI to see my preset :) and if it is posssible have option to "publish" the loadout for share it with new players. 

Maybe, with something like that, you can have both cases: were players can lose time and feel 'cool' and the case were the admin wants to have restricted/packed loadouts (the published/shared ones). (maybe a boolean to disable the option of personal loadouts for some communities)

Maybe i am just asking for the same system that we have right now but with costs. I guess something like this https://github.com/7erra/Arsenal-Shop but with the ACE arsenal, instead of vanilla. (and with the chance to save the loadout to re-buy it fast).

**Comment by Wyqer** [comment]
Just as clarification:

> We discussed internally about an alternative to this approach as an optional (default disabled) addition to the virtual arsenal.

So we won't implement something in the virtual/ace arsenal which is like a "shop" for players. One reason the needed work for this and especially as there will be many "My players spend all our resources, I want to restrict this, it should be configurable this and that way, some technical solution as we won't talk to each other and set own rules/conventions" (extreme example, of course).
So the "optional (default off) alternative" will be something which will remove the arsenal.
Just to make sure: It will be a setting for the admin to enable (like switching the arsenal preset).

**Comment by syncy34** [comment]
This is the reason why i thought about the Arsenal like Antistasi but i totaly understand that this means to much work besides your other goals.

So i think the second option would be ok. In this case one can build up a static resupply point inside of an fob or transport the crate to a fireteam.

In case of option two i would say to use category prizes. This reduces the time needed to configure the mission and makes it easier for admins.

Thank you for overthinking this request and for bringing in this effort :)

**Comment by HeliceWolf** [comment]
I understand the reasons. I would like have enough programming skills to help. 

Could be possible a method to import the ace preset loadouts to the crate presets? Maybe this can solve it in a easiest way.

**Comment by MissVerstanden** [comment]
I am a little late to the party but just stumbled upon this, so here is a few ideas:
it might involve defining quite a few things but since it is optional whoever wants to use it has to cope with a one time setup time only so please hear me out:
Every role from the lobby (re)spawns with a sensible but basic loadout, this is editable in the Eden editor.
Additional equipment is bought in crates as you suggested.
However in order to be able to buy crates the player/commander needs to build building(s) first and the crates cost ressources.
The access to gear could be tiered and you have to upgrade a building to get access to higher tier crates.
Of course the big problem is configuring the contents of these crates, especially if you go for a tiered system (could be optional). If you leave out the tier system you can probably get by with the crates that are already present in the game.
