### ISSUE TITLE
Feature Suggestion: Commander airdrops

### ISSUE THREAD

**Issue by FatRefrigerator** [KillahPotatoes/KP-Liberation#61]
Apple and I have been talking about a system where the commander can call in airdrops of small vehicles or paratroopers while in the field. 

The commander would have a menu option he can call up at any time with multiple options for what to drop and how to drop it. The commander selects a vehicle and the drop method and then a map appears where the commander can choose to have it drop. This allows the commander to give reinforcements to troops even if he's not directly engaged in combat, and he can place it precisely where they want.

For the sake of realism and gameplay there would be two dropping options:

 The first one would be to spawn a Chinook at around 3-4km out since most players' draw distances are about 2km and then fly to the location and drop the cargo while flying (not fast, but not completely stopped). This would look realistic, but also add the necessity of clearing out enemy AA first. This option would be more expensive than it would be to buy it at the FOB (the cost could be the regular cost + 50% of the fuel cost for a Chinook. Possibly costing even more if the Chinook is shot down).

The second option would be the easiest to implement, but not feel as real. It would simply be the "noise and drop" like you have when you deploy a FOB and supplies drop. This would cost more than the Chinook drop and have a delay before the supplies drop since they're being dropped by a C130 from a far away airbase and not the "Chinook from Base Chimera". This would be immune to enemy AA, but like I said it would cost more and possibly take longer, since it will have a delay and be falling from a higher height.

These drops would be limited to Humvee's and smaller vehicles and infantry squads.

**Comment by Wyqer** [comment]
Could be a nice feature, yes.
But I personally would suggest to restrict it in that way, that the commander has to be at a FOB. Like for the production and logistic actions. So he has to be "near a long range communication"

**Comment by FatRefrigerator** [comment]
How about make it so the Commander has to be in range of a friendly Radio Tower?

**Comment by Wyqer** [comment]
In general the role of the commander is:
Stay in one of your FOBs
Command your player groups
Command possible AI groups via Zeus
Manage Production
Manage Logistic
Build the FOB buildings

Sure, for smaller group the player will be in the field, for sure. But the above is the basic and general thought behind the commander role and his functionalities.

Adding a friendly RT is some kind of option, yes.

**Comment by FatRefrigerator** [comment]
Oh see there's your problem. No person is going to be like "I'm gonna play some Arma today, but instead of playing I'm just gonna stand at the FOB".

**Comment by Wyqer** [comment]
"No person is going to be like" is wrong. Maybe not most players want that, but some for sure. Our group for example plays that way and some other milsim orientated groups also.
And of course I don't describe the "general role aspect" out of nowhere ^^
But sure, for the more casual players that won't happen. But FOB and RT as "has to be near" points sounds good.
And by the way it would be a new feature, not a adjustment of a existing one.

**Comment by Applejakerie** [comment]
Being near an FOB, that must have a priced comms type object/building. Or being within range of a captured RT. That'd be my choice of prerequisites.

**Comment by FatRefrigerator** [comment]
Yeah when I say "most people" I mean small groups. Because when I search "Liberation" in the server browser only once have I found a server with more than 10 people. So I assume most groups are smaller.

**Comment by SondreBakken** [comment]
I like the fact that you would get the radio for support option as long as you are within the range of a controlled radiotower. Also, would be realistic if the airborn support respawned over the USS Freedom. Then you would also have to take the distance into consideration when waiting for support

**Comment by Mike2306** [comment]
Could also solve #267

**Comment by SondreBakken** [comment]
I have to argue that having a remote controlled commander will be a better solution. As I see it you can do all of this as long as you have someone in base that can send AI reinforcements either by land or air and it will carry forward Christians thoughs on this (where someone should be in the fob).

The remote controlled Fob commander will not change the way Christian intended this to be played.
It will just be easier for smaller groups or groups where no one wants to remain in fob to enjoy the full gameplay possibilities of the scenario. (Sending land/air pickups, air/land/drone support, or artillery from a chosen FOB). All these will be available and the player will have full freedom within the scenario ruleset.

If implementing drops I see this as code and functionality that will have to be maintained seperately. It will also leave some restrictions on players because you will only implement things that seem to be ideal to most people. For example I started using utility drones to resupply my snipers, or send first aid packages when treating civilians. Will this have to be implemented as a separate thing? With the remote fob commander you get these things automatically.

The remote controlled commander function will also just use what is already there of building system, resource system etc.
Then you wont have issues around where to spawn things in base if automatically spawned, or which fob to take resource from when calling in an heli pickup etc.

**Comment by Wyqer** [comment]
I'll have a look at the suggestion #267 
Haven't tested it yet, so just a thought I've to check: Isn't it already possible to access this functionality if you just leave one AI soldier in the FOB and access him via zeus remote control?

**Comment by SondreBakken** [comment]
Good point. As is now Zeus remote control is disabled I guess?
