### ISSUE TITLE
Vehicles exploding/moving/vanishing on server start

### ISSUE THREAD

**Issue by skypartan** [KillahPotatoes/KP-Liberation#724]
### Basic Information

**Mission version:**
0.96.6

**Map used:**
Altis

**Mods used:**
Advanced Urban Rappeling
BWMod
CBA_A3
Enchanced Movement
FA-18 Super Hornet
RHSAFRF
RHSUSAF

**Dedicated or local game:**
Dedicated

**Source of the mission file (URL):**
https://github.com/KillahPotatoes/KP-Liberation/releases/download/v0.96.6/kp_liberation.Altis.zip

### Individual Things
**Did you edit anything within the mission files?**
Yes

**If yes, what did you edit exactly?**
Changed the default value of LoadSaveParams in mission_params.hpp to 2

### Short Issue Description
When starting the server, some vehicles (mainly planes inside hangars) spawn destroyed or in wrong places. Sometimes the planes don't spawn at all.

### Expected Behaviour

All vehicles should spawn in the places they were when shutting down the server (if they are inside the FOB areas).

### Steps to Reproduce the Issue

Place land vehicles near each other and restart server.
Place planes (F-18 Super Hornet / A-164 Wipeout) inside tent hangar and restart server.

### Screenshots, Serverlog or any other helpful Information
From my tinkering with the source code I think I found the cause, but wasn't able to fix it. Looks like some of the vehicles spawn with the wheels inside the floor, causing them to move wrongly (destryoing near vehicles) or go underground. Sometimes the F-18 appeared for an instant inside the ceiling of the hangar, before moving to the right place inside it.

**Comment by tyl3r99** [comment]
I had the same issue on some previous versions using the wipeout plane. It would just go nuts and shoot off up into the sky and blow up. Happened about 80% of the time on mission start. 

I made sure it was 100% flat ground with no nearby assets or environmental objects

**Comment by Wyqer** [comment]
Could be an issue with the mod vehicle itself, if you say it's sometimes spawning inside the floor with the weels or similar.
Personally I can't reproduce that issue with vanilla planes parked in the tent hangar.

Concerning vanishing jets: this can happen sometimes if you've changed the loadout. Can't reliably reproduce this, but it seems to be one possible cause of a vanishing plane during server restarts.

So for modded vehicles like the FA-18 it's more sensible to just don't park it inside the hangar than investing much time to track the cause down and maybe just come up with "yes, it's caused by the mod vehicle itself, nothing we can do".
