### ISSUE TITLE
Encore Radar AI

### ISSUE THREAD

**Issue by s3599835** [KillahPotatoes/KP-Liberation#732]
### Basic Information
**Mission version:** 
0.96.6
**Map used:**
Altis
**Mods used:**
Blastcore, Server-side smoke for blastcore, C2 Command & Control, JSRS, CBA, Enhanced Movement, Bloodlust
**Dedicated or local game:**
Dedicated
**Source of the mission file (URL):**
Github Release
### Individual Things
**Did you edit anything within the mission files?**
Yes
**If yes, what did you edit exactly?**
Changed default FOB building from Land_Cargo_HQ_V1_F to Land_Cargo_Tower_V1_F.
### Short Issue Description
When spawning in an AN/MPQ-105 Radar as Flight control in a FOB, the AI inside it refuses to turn on the radar (i.e. as a player, pressing Ctrl+R). Even by moving the unit into your squad and telling them to turn it on, they turn it back off instantaneously. 
This obviously affects using the MIM-145 for AA defence, as without the Radar AI actually turning the radar on, they cannot lock on to targets for the SAM to fire at.
It can be remedied by taking manual control of the radar and locking targets yourself, however I personally would like it to be an autonomous defence for when I'm not at the FOB and it comes under attack. 
### Expected Behaviour
Radar AI should turn their radar on and lock up air targets automatically for the SAM launcher to engage.
### Steps to Reproduce the Issue

1. Buy AN/MPQ-105 Radar (Flight control) from Build menu.
2. Use Zeus to bring the unit in to your squad so you can issue it orders
3. Select the unit and tell it to turn on its radar (6 -> 1)
4. The unit will turn its radar off straight away

### Screenshots, Serverlog or any other helpful Information

Unit is also stuck in careless mode and this cannot be overwritten. Not sure if this has something to do with it. It will still track targets in careless, but won't turn the radar on and lock them up.

**Comment by Wyqer** [comment]
The careless is indeed due to the fact that it's a UAV. As you already mentioned, it still tracks and attacks enemies (e.g. the autonomous mg).
During a small test, even if the radar isn't turned on, the radar tracked a jet flying by and the SAM site shot it down.
`vehicleReportRemoteTargets` is also enabled on the radar UAVs, so it shares his data correctly.
`setVehicleRadar` on the object on the other hand doesn't seem to work if you use `1` to force it on.
From the current perspective and reproduction it's Arma related and kind of working even if it doesn't seem like that due to disabled radar. At least it's nothing which would be researched further at the moment.
If anybody is up to dive deeper in this, feel free to report the results.
