### ISSUE TITLE
Enhance the permission system

### ISSUE THREAD

**Issue by Mike2306** [KillahPotatoes/KP-Liberation#95]
It would be good to have some more options in the permissions menu.

For example allow others to recruit only infantry instead of disabling the whole build menu for them.

**Comment by Wyqer** [comment]
I'll have look to split it a little bit for the next version. Will need some deeper changes from depending things, so it wouldn't be a "one hour" thing. But it's a good idea, yeah.

**Comment by SondreBakken** [comment]
I will just add on here that it would be really great if the permission menu had the option to allow other players to have the crew option (where they can build non squad infantry and predefined squads)

**Comment by Wyqer** [comment]
Why basicly should players be able to build crewed vehicles or whole AI squads?
Only the commander can command them, because atm only he can build things which are only "usable" by himself.

**Comment by SondreBakken** [comment]
Well, maybe expand the permission menu to let others have the commander role aswell.  Some might want to share that role.  We are few people playing so it would be nice for me to share that role so I am not the only one that can send support or crewed vehicles / helis

When we use the advanced Command AI you can color code the squads and waypoints. We use that to show who is using what and controlling what. It works really well and expand the gameplay a lot.

Situations where this would be ideal is: I am far from the FOB (I am the commander) and I need a heli transport. Then I could hear if someone is in the fob, ask them to place a crewed heli which I could just ask to come pick me up. 

Another example is during a attack on a bigger city. Our tank support is gone. I am in the middle of some close quarter battle. My friend respawns back in the FOB. Would be nice if he had the possibility to put out some squads and crewed vehicles and send into the battle instead of me force respawning because I am the only on that can do it.

**Comment by doodzio** [comment]
I suggest to take UNFLIP out from others where it's grouped with e.g. side missions menu.

**Comment by Wyqer** [comment]
I'm thinking about altering the permission screen to something like a "player manager" screen. With a list on the left and on the right many information (last online, killed people and other statistics) and a much deeper permission control for each player. But it's still under the "no priority". First I've to finish the civrep and enemy behaviour.

**Comment by chrisleaptrott** [comment]
My group was looking into trying to get the permissions to manage down to the type, and also split the build on unarmed vehicles and armed down further. We'd be okay with some people building light vehicles, but not tanks, littlebirds, but not jets. Etc etc.
Looking into the code as well myself, will report back if I or my fellow code-monkeys make any headway.

**Comment by Wyqer** [comment]
Any contributions concerning this suggestion are always appreciated.
I would look at this and implement are more detailed permission system later on, of course. But currently I don't give it a high priority in relation to the other things I want to implement.
So if you have a good working code and would like to contribute it, it would speed things up and after I've reviewed/tested it, I would merge it.

**Comment by madpat3** [comment]
just leave the cammanderslot as it is, but make it possible to give certain permissions to people inside the whitelist, by default (entries inside the script/kp_liberation_config.sqf)

**Comment by SondreBakken** [comment]
I have to argue that having a remote controlled commander will be a better solution. As I see it you can do all of this as long as you have someone in base that can send AI reinforcements either by land or air and it will carry forward Christians thoughs on this (where someone should be in the fob). 

The remote controlled Fob commander will not change the way Christian intended this to be played.
 It will just be easier for smaller groups or groups where no one wants to remain in fob to enjoy the full gameplay possibilities of the scenario. (Sending land/air pickups, air/land/drone support, or artillery from a chosen FOB). All these will be available and the player will have full freedom within the scenario ruleset.

If implementing drops I see this as code and functionality that will have to be maintained seperately. It will also leave some restrictions on players because you will only implement things that seem to be ideal to most people. For example I started using utility drones to resupply my snipers, or send first aid packages when treating civilians. Will this have to be implemented as a separate thing? With the remote fob commander you get these things automatically.

The remote controlled commander function will also just use what is already there of building system, resource system etc. 
Then you wont have issues around where to spawn things in base if automatically spawned, or which fob to take resource from when calling in an heli pickup etc.

**Comment by ZwinkaDink** [comment]
me and a buddy are looking into adding ExtDB to this and store permissions and other info on a DB to make it easier to give permissions in the mission.
